version: "3.8"

services:
  backend:
    image: management:latest
    container_name: my-app
    networks:
      - my_app
    ports:
      - "8080:8080"
    depends_on:
      - db_postgres
  db_postgres:
    image: postgres:latest
    container_name: my_db
    environment:
      - POSTGRES_DB=market
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=root123
    ports:
      - "5433:5432"
    networks:
      - my_app
networks:
  my_app:
