spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/port
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: husanchoriyev20040406@gmail.com
    password: dbvf bidy znpp fqxi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
api:
  version: v15
jwt:
  secret: my-secret-key-for-jwt-please-do-not
  expire-time: 864 000 000 # 10 DAY in milliseconds

