### Add Meal
POST http://localhost:8080/meal/create
Authorization: Bearer {eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaG9yaXlldmh1c2FuNzRAZ21haWwuY29tIiwiZXhwIjoxNzU2MDU0NzA2fQ.1hJITWPpbcb78klSmTLkcPfybXjgswz_bC-ZY-8WCVQ
Content-Type: application/json

{
  "name": "Mini Lavash",
  "description": "A delicious mini lavash with fresh ingredients.",
  "price": 50.0,
  "category": "Fast Food",
  "imageUrl": "http://example.com/lavash.jpg",
  "chickenId": 1
}

##################################
### Get All Meals
GET http://localhost:8080/meal/get-list?page=1&size=2
Authorization: Bearer {eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaG9yaXlldmh1c2FuNzRAZ21haWwuY29tIiwiZXhwIjoxNzU1MTc3MjMzfQ.cgjv5S-76IYNK89l3GfIOxPLWCQ4vUqtjQ023lWrKo8

##################################
### Put Meal
### Update Meal by ID
##################################
PUT http://localhost:8080/meal/update?mealId=1
Authorization: Bearer {eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaG9yaXlldmh1c2FuNzRAZ21haWwuY29tIiwiZXhwIjoxNzU2MDU0NzA2fQ.1hJITWPpbcb78klSmTLkcPfybXjgswz_bC-ZY-8WCVQ
Content-Type: application/json

{
  "name": "Osh",
  "description": "This is a delicious Osh with fresh ingredients.",
  "price": 150.0,
  "category": "Pasta",
  "imageUrl": "http://example.com/new-image.jpg",
  "chickenId":5
}

##################################
### Delete Meal
### Delete Meal by ID
##################################
DELETE http://localhost:8080/meal/delete?id=2
Authorization: Bearer {eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaG9yaXlldmh1c2FuNzRAZ21haWwuY29tIiwiZXhwIjoxNzU1MTc3MjMzfQ.cgjv5S-76IYNK89l3GfIOxPLWCQ4vUqtjQ023lWrKo8